# language: node_js
# node_js:
#   - 12

# cache: npm

# before_install:
#   - npm i -g npm@6.13.4

# install:
#   - npm ci

# before_script:
#   - npm start & wait-on http://localhost:3000

# script:
#   - npm run cy:run
#   - npm run build
